name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  # Firebase Authentication
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0

  # UI and Utility Packages
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # OpenStreetMap Packages
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0

  # Location and Background Services
  geolocator: ^10.1.0
  workmanager: ^0.9.0+3

  # Timeline UI
  timeline_tile: ^2.0.0

  # Database
  sqflite: ^2.3.3
  path: ^1.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
   
  assets:
    - assets/images/logo.png