// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKcWigITWPAVMDm4kumqksijX7dwrqIk0',
    appId: '1:214949487871:web:d3a1047d1ab5c295d5d8ca',
    messagingSenderId: '214949487871',
    projectId: 'tripster-1dd90',
    authDomain: 'tripster-1dd90.firebaseapp.com',
    storageBucket: 'tripster-1dd90.firebasestorage.app',
    measurementId: 'G-VMRYL5LWQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF4uGHJSHYl14rbCvK-sCeMticllZMbOA',
    appId: '1:214949487871:android:d72f2ac2af6af607d5d8ca',
    messagingSenderId: '214949487871',
    projectId: 'tripster-1dd90',
    storageBucket: 'tripster-1dd90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2hFfZkU3LOaIm2lF_PkFmQaVNApa1bT4',
    appId: '1:214949487871:ios:f407f5b4f8ef78eed5d8ca',
    messagingSenderId: '214949487871',
    projectId: 'tripster-1dd90',
    storageBucket: 'tripster-1dd90.firebasestorage.app',
    iosClientId: '214949487871-6pm7ncg6hfj3tpdkh42peq9e7molmdrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2hFfZkU3LOaIm2lF_PkFmQaVNApa1bT4',
    appId: '1:214949487871:ios:f407f5b4f8ef78eed5d8ca',
    messagingSenderId: '214949487871',
    projectId: 'tripster-1dd90',
    storageBucket: 'tripster-1dd90.firebasestorage.app',
    iosClientId: '214949487871-6pm7ncg6hfj3tpdkh42peq9e7molmdrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKcWigITWPAVMDm4kumqksijX7dwrqIk0',
    appId: '1:214949487871:web:bcd9e54d19a366a8d5d8ca',
    messagingSenderId: '214949487871',
    projectId: 'tripster-1dd90',
    authDomain: 'tripster-1dd90.firebaseapp.com',
    storageBucket: 'tripster-1dd90.firebasestorage.app',
    measurementId: 'G-0BQ3NF6Z4M',
  );

}